[package]
name = "multi3"
version = "2.0.0-async"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "*"
serde = { version = "*", features = ["derive"] }
tokio = { version = "*", features = ["full"] }
clap = { version = "*", features = ["derive"] }
derive_more = { version = "*", features = ["full"] }
time = { version = "*" }

tokio-rustls = { version = "*" }
webpki-roots = { version = "*" }
rcgen = { version = "*", features = ["x509-parser"] }
log = "0.4.29"
env_logger = "0.11.10"
ratatui = "0.30.0"
crossterm = "0.29.0"

[profile.release]
opt-level = 's'
lto = "thin"
codegen-units = 1
panic = "abort"
